name: flutter_nfc
description: A nfc reader plugin for android.
version: 0.0.1
author: Dou Dou
homepage: https://github.com/doudouaixiaoyu/flutter_nfc.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.yu.flutter_nfc
    pluginClass: FlutterNfcPlugin